project:
  type: book

lang: zh

book:
  title: "R 语言数据科学实战"
  output-file: "data-science-in-action"
  author: "统计之都团队"
  repo-actions:
    - source
  repo-url: "https://github.com/XiangyunHuang/data-science-in-action"
  chapters:
    - index.qmd
    - intro.qmd
    - data-visualization.qmd
    - references.qmd
  repo-branch: main
  search: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    cover-image: cover.png
    code-link: true
    code-line-numbers: true
    crossref:
      chapters: true
  docx:
    toc: true
    toc-depth: 3
    crossref:
      chapters: true
  pdf:
    documentclass: book
    include-in-header: preamble.tex
    classoption: [UTF8,twoside,openany,table]
    keep-tex: true
    lof: true
    lot: true
    geometry:
      - tmargin=2.5cm
      - bmargin=2.5cm
      - lmargin=3.0cm
      - rmargin=2.0cm
    highlight-style: github
    number-sections: true
    top-level-division: chapter
    colorlinks: true
    link-citations: true
    crossref:
      chapters: true

editor: source

