project:
  type: book
  output-dir: _book

lang: zh

book:
  title: "R 语言数据分析实战"
  date: today
  date-format: long
  output-file: "_main"
  author: "统计之都团队"
  repo-actions:
    - source
  repo-url: "https://github.com/XiangyunHuang/data-analysis-in-action"
  downloads: [pdf, epub, docx]
  google-analytics: "G-ZPWJBMKFL8"
  comments:
    giscus:
      repo: XiangyunHuang/data-analysis-in-action
  chapters:
    - index.qmd
    - preface.qmd
    - intro.qmd
    # - part: "软件配置"
    #   chapters:
    #     - setup-r.qmd
    #     - setup-rstudio.qmd
    #     - setup-vscode.qmd
    - part: "数据准备"
      chapters:
        - wrangling-objects.qmd
        - wrangling-collection.qmd
        - wrangling-cleaning.qmd
        - wrangling-manipulation.qmd
        - wrangling-processing.qmd
    - part: "数据探索"
      chapters:
        - visualization-basic.qmd
        - visualization-gallery.qmd
        - visualization-practice.qmd
        - visualization-summary.qmd
    - part: "数据交流"
      chapters:
        - interactive-graphics.qmd
        - interactive-tables.qmd
    #     - interactive-applications.qmd
        - documents-html.qmd
    #     - documents-latex.qmd
    #     - documents-office.qmd
    #     - documents-workflow.qmd
    # - part: "数据建模"
    #   chapters:
    #     - modeling-linear.qmd
    #     - modeling-generalized-linear.qmd
    #     - modeling-mixed-effects.qmd
    #     - modeling-nonlinear.qmd
    #     - modeling-data-mining.qmd
    #     - modeling-neural-networks.qmd
    # - part: "分析实战"
    #   chapters:
    #     - analyze-network-data.qmd
    #     - analyze-text-data.qmd
    #     - analyze-time-series-data.qmd
    #     - analyze-spatial-data.qmd
    - references.qmd
    #   # advanced-topics
  appendices:
  #   - statistical-inference.qmd
    - statistical-computation.qmd
  #   - statistical-simulation.qmd
  repo-branch: main
  search: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    cover-image: cover.png
    code-link: true
    code-line-numbers: true
    crossref:
      chapters: true
  docx:
    toc: true
    toc-depth: 3
    crossref:
      chapters: true
  epub:
    toc: true
    toc-depth: 3
    epub-cover-image: cover.png
    html-math-method: mathml
    crossref:
      chapters: true
  pdf:
    documentclass: book
    include-in-header: preamble.tex
    classoption: [UTF8,twoside,openany,table]
    keep-tex: true
    lof: true
    lot: true
    geometry:
      - tmargin=2.5cm
      - bmargin=2.5cm
      - lmargin=3.0cm
      - rmargin=2.0cm
    highlight-style: github
    number-sections: true
    top-level-division: chapter
    colorlinks: true
    link-citations: true
    crossref:
      chapters: true

editor: source

