project:
  type: book
  output-dir: _book

lang: zh

book:
  title: "R 语言数据分析实战"
  date: today
  date-format: long
  output-file: "_main"
  author: "统计之都团队"
  repo-actions:
    - source
  repo-url: "https://github.com/XiangyunHuang/data-analysis-in-action"
  downloads: [pdf, epub, docx]
  google-analytics: "G-ZPWJBMKFL8"
  comments:
    giscus:
      repo: XiangyunHuang/data-analysis-in-action
  chapters:
    - index.qmd
    - preface.qmd
    - intro.qmd
    # - part: getting-started.qmd
    #   chapters:
    #     - setup-r.qmd
    #     - setup-rstudio.qmd
    #     - setup-vscode.qmd
    #     - data-structure.qmd
    #     - programming-basics.qmd
    # - part: data-wrangling.qmd
    #   chapters:
    #     - data-collection.qmd
    #     - data-manipulation.qmd
    #     - data-processing.qmd
    - part: "数据可视化"
      chapters:
        - visualization-basic.qmd
        - visualization-gallery.qmd
        - visualization-practice.qmd
        - visualization-summary.qmd
    # - part: data-communication.qmd
    #   chapters:
    #     - interactive-graphics.qmd
    #     - interactive-tables.qmd
    #     - interactive-applications.qmd
    #     - documents-html.qmd
    #     - documents-latex.qmd
    #     - documents-office.qmd
    #     - documents-workflow.qmd
    # - part: data-modeling.qmd
    #   chapters:
    #     - modeling-linear.qmd
    #     - modeling-generalized-linear.qmd
    #     - modeling-nonlinear.qmd
    #     - modeling-mixed-effects.qmd
    #     - modeling-data-mining.qmd
    #     - modeling-neural-networks.qmd
    #   # applications
    # - part: "项目管理"
    #   chapters:
    #     - project-pipeline.qmd
    #     - project-environments.qmd
    #     - project-rocker.qmd
    #     - project-version.qmd
    # - part: domain-specific-analysis.qmd 
    #   chapters:
    #     - analyze-network-data.qmd
    #     - analyze-text-data.qmd
    #     - analyze-time-series-data.qmd
    #     - analyze-spatial-data.qmd
    #   # advanced-topics
    # - part: miscellaneous-topics.qmd
    #   chapters:
    #     - statistical-inference.qmd
    #     - statistical-computation.qmd
    #     - statistical-simulation.qmd
    - references.qmd
  repo-branch: main
  search: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    cover-image: cover.png
    code-link: true
    code-line-numbers: true
    crossref:
      chapters: true
  docx:
    toc: true
    toc-depth: 3
    crossref:
      chapters: true
  epub:
    toc: true
    toc-depth: 3
    epub-cover-image: cover.png
    html-math-method: katex
    crossref:
      chapters: true
  pdf:
    documentclass: book
    include-in-header: preamble.tex
    classoption: [UTF8,twoside,openany,table]
    keep-tex: true
    lof: true
    lot: true
    geometry:
      - tmargin=2.5cm
      - bmargin=2.5cm
      - lmargin=3.0cm
      - rmargin=2.0cm
    highlight-style: github
    number-sections: true
    top-level-division: chapter
    colorlinks: true
    link-citations: true
    crossref:
      chapters: true

editor: source

