project:
  type: book
  output-dir: _book

lang: zh

book:
  title: "R 语言数据分析实战"
  date: today
  date-format: long
  output-file: "_main"
  author: "黄湘云"
  repo-actions:
    - source
  repo-url: "https://github.com/XiangyunHuang/data-analysis-in-action"
  downloads: [pdf]
  # downloads: [pdf, epub, docx]
  google-analytics: "G-ZPWJBMKFL8"
  # comments:
  #   giscus:
  #     repo: XiangyunHuang/data-analysis-in-action
  chapters:
    - index.qmd
    - preface.qmd
    - intro.qmd
    # - part: "软件配置"
    #   chapters:
    #     - setup-r.qmd
    #     - setup-rstudio.qmd
    #     - setup-vscode.qmd
    - part: "数据准备"
      chapters:
        - wrangling-objects.qmd
        - wrangling-collection.qmd
        - wrangling-cleaning.qmd
        - wrangling-manipulation.qmd
        - wrangling-processing.qmd
    - part: "数据探索"
      chapters:
        - visualization-basic.qmd
        - visualization-intermediate.qmd
        - visualization-advanced.qmd
        - visualization-lattice.qmd
        - visualization-graphics.qmd
        - visualization-tikz.qmd
        - visualization-practice.qmd
    - part: "数据交流"
      chapters:
        - interactive-graphics.qmd
        - interactive-tables.qmd
        - interactive-applications.qmd
        - documents-html.qmd
        - documents-latex.qmd
        - documents-office.qmd
    - part: "统计分析"
      chapters:
        - common-statistical-tests.qmd
        - regression-and-correlation.qmd
        - categorical-data-analysis.qmd
        - power-analysis.qmd
    - part: "数据建模"
      chapters:
        - analyze-network-data.qmd
        - analyze-text-data.qmd
        - analyze-survival-data.qmd
        - analyze-time-series-data.qmd
        - analyze-point-pattern.qmd
        - analyze-spatial-data.qmd
        - analyze-areal-data.qmd
    - part: "优化建模"
      chapters:
        - statistical-computation.qmd
        - numerical-optimization.qmd
        - optimization-problems.qmd
    - part: "贝叶斯建模"
      chapters:
        - probabilistic-reasoning-framework.qmd
        - generalized-linear-models.qmd
        - hierarchical-normal-models.qmd
        - mixed-effects-models.qmd
        - generalized-additive-models.qmd
        - gaussian-processes-regression.qmd
        - time-series-regression.qmd
    - part: "机器学习"
      chapters:
        - classification-problems.qmd
        - clustering-problems.qmd
        - regression-problems.qmd
    - references.qmd
  appendices:
    - notations.qmd
    - matrix-operations.qmd
    - git-github.qmd
  repo-branch: main
  search: true

bibliography: 
  - references.bib
  - packages.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    include-in-header:
      - header.html
    toc: true
    toc-depth: 3
    cover-image: cover.png
    code-link: true
    code-line-numbers: true
    crossref:
      chapters: true
  # docx:
  #   toc: true
  #   toc-depth: 3
  #   crossref:
  #     chapters: true
  # epub:
  #   toc: true
  #   toc-depth: 3
  #   epub-cover-image: cover.png
  #   html-math-method: mathml
  #   crossref:
  #     chapters: true
  pdf:
    documentclass: book
    include-in-header: preamble.tex
    include-before-body:
      text: |
        \ifdefined\appendixname
          \renewcommand*\appendixname{附录}
        \else
          \newcommand\appendixname{附录}
        \fi
    include-after-body:
      text: |
        \printindex
        % \printnoidxglossary[sort=word,title={术语表}]
    classoption: 
      - UTF8
      - twoside
      - openany
      - table
    keep-tex: true
    latex-auto-install: false
    mathspec: true
    lof: true
    lot: true
    geometry:
      - tmargin=2.5cm
      - bmargin=2.5cm
      - lmargin=3.0cm
      - rmargin=2.0cm
    hyperrefoptions:
      - pdfstartview=FitH
      - linktoc=all
    highlight-style: github
    number-sections: true
    top-level-division: chapter
    colorlinks: true
    link-citations: true
    crossref:
      chapters: true

editor: visual

