# 空间数据分析 {#analyze-spatial-data}

```{r}
library(nlme)
library(ggplot2)
library(gstat)
library(sf)
library(abind)
library(stars)
```

```{r}
#| label: tbl-rongelap-nuclear-data
#| tbl-cap: "朗格拉普岛核辐射检测数据及海岸线坐标数据"
#| tbl-subcap:
#|   - "核辐射检测数据"
#|   - "海岸线坐标数据"
#| layout-ncol: 2
#| code-fold: true
#| echo: !expr knitr::is_html_output()

# 加载数据
rongelap <- readRDS(file = "data/rongelap.rds")
rongelap_coastline <- readRDS(file = "data/rongelap_coastline.rds")

library(knitr)
knitr::kable(head(rongelap, 6),
  col.names = c("横坐标", "纵坐标", "数目", "时间")
)
knitr::kable(head(rongelap_coastline, 6),
  col.names = c("横坐标", "纵坐标")
)
```

## 模型拟合

下面采用 **nlme** 包的 `gls(`) 函数拟合模型，该函数使用广义最小二乘方法估计模型的参数。

```{r}
library(nlme)
# 无块金效应
fit_rongelap_gls <- nlme::gls(
  model = log(counts / time) ~ 1, data = rongelap,
  correlation = nlme::corExp(form = ~ cX + cY, nugget = F)
)
summary(fit_rongelap_gls)

# 块金效应
fit_rongelap_gls2 <- nlme::gls(
  model = log(counts / time) ~ 1, data = rongelap,
  correlation = nlme::corExp(form = ~ cX + cY, nugget = T)
)
summary(fit_rongelap_gls2)
```

## 空间操作

将 data.frame （data frame 二维表格）类型数据转为 sf （simple feature 空间几何数据）类型的数据，通过对研究岛屿的网格化，获得预测位置。

```{r}
library(sf)
library(abind)
library(stars)
# 准备数据
rongelap_sf <- st_as_sf(rongelap, coords = c("cX", "cY"), dim = "XY")
rongelap_coastline_sf <- st_as_sf(rongelap_coastline, coords = c("cX", "cY"), dim = "XY")
rongelap_coastline_sfp <- st_cast(st_combine(st_geometry(rongelap_coastline_sf)), "POLYGON")
# 网格化
rongelap_grid_stars <- st_bbox(rongelap_coastline_sfp) |>
  st_as_stars(dx = 32, dy = 16) |>
  st_crop(rongelap_coastline_sfp)
rongelap_grid_stars
```

## 插值预测

下面采用 gstat 包的 krige 函数，该函数实现了 Kriging 克里金插值预测方法，该预测方法只适用于研究区域内，而不能外推到研究区域外。

```{r}
# 变差
library(gstat)
fit_rongelap_gstat <- fit.variogram.reml(log(counts / time) ~ 1,
  locations = ~ cX + cY, data = rongelap,
  model = vgm(psill = 1, model = "Exp", range = 169.7472, nugget = 1)
)
fit_rongelap_gstat

# 预测
fit_krige_pred <- krige(
  formula = log(counts / time) ~ 1, 
  locations = rongelap_sf,
  newdata = rongelap_grid_stars, 
  model = fit_rongelap_gstat
)
fit_krige_pred
```

展示克里金插值方法预测整个岛屿核辐射强度

```{r}
#| label: fig-kriging-prediction-gstat
#| fig-cap: 核辐射强度的预测值
#| fig-showtext: true
#| fig-width: 6
#| fig-height: 3.5

library(ggplot2)

ggplot() + 
  geom_stars(data = fit_krige_pred, aes(fill = exp(var1.pred)), 
             na.action = na.omit) + 
  scale_fill_distiller(palette = "Spectral") +
  theme_bw() +
  labs(x = "横坐标", y = "纵坐标", fill = "预测值")
```

克里金插值方法的预测方差

```{r}
#| label: fig-kriging-variance-gstat
#| fig-cap: 克里金插值预测方差
#| fig-showtext: true
#| fig-width: 6
#| fig-height: 3.5

ggplot() + 
  geom_stars(data = fit_krige_pred, aes(fill = var1.var), 
             na.action = na.omit) + 
  scale_fill_distiller(palette = "Spectral") +
  theme_bw() +
  labs(x = "横坐标", y = "纵坐标", fill = "预测方差")
```
