# HTML 文档 {#sec-documents-html}

从本章开始，接下来的三个章节都围绕数据交流的工具及其案例展开。日常工作中，有的需要产出具有丰富交互内容的网页文档（HTML 文档），有的需要产出排版精美、符合格式要求的、可打印的便携式文档（PDF 文档），有的需要可协作共享、可编辑修改的办公文档（Office 文档）。在 R 语言社区，陆续出现两套解决方案，一个是以 rmarkdown 包为核心的 R Markdown 生态，另一个是以 Quarto 为核心的文档写作和发布系统。继 R Markdown 出现 10 余年后，2022 年 RStudio 公司发布 Quarto 系统，整合 R Markdown 生态，提供统一的语法。截止写作时间，相比于成熟的 R Markdown 生态，Quarto 系统还在路上。因此，不拘泥于 R Markdown 还是 Quarto，根据使用场景、实践经验、工具现状，选择最合适的工具介绍，整体上，以 Quarto 为主，R Markdown 补位的方式介绍。


## 基础元素 {#sec-foundation}

无论是 R Markdown 还是 Quarto，都是站在巨人 Pandoc 的肩膀上，Pandoc 在普通 Markdown 的基础上提供了许多扩展支持，通过一些简单的标记，大大丰富了文档内容，下面介绍的内容适用于 R Markdown 和 Quarto，无论文档最终的输出格式如何。


### 样式 {#sec-style}

文字样式，如加粗、倾斜、上色、缩小、放大、上下标等


### 图表 {#sec-figure}

其一插入代码生成的图片，其二导入外部制作好的现成图片。

Markdown 表格、knitr 制作的表格

### 列表 {#sec-list}

常见的列表有无序列表、有序列表及其嵌套。



### 引用 {#sec-cross-references}

除了引用外部书籍、文章、刊物等的内容，还有长文档内部的交叉引用，这项功能是非常需要的，涉及图、表、公式、定理，参考文献，列表条目等。

有序的列表环境，通篇计数

(@good)  第一个人是好人 (1).
(@bad)  第二个人是坏人 (2).
(@ugly)  第三个人是丑陋的 (3).

在 `(@)` 中添加标识符，如 `(@good)` 就可以引用列表中的条目 (@good)。


## 制作报告 {#sec-quarto-report}


Quarto Report 文档

## 制作演示 {#sec-quarto-presentation}

Quarto Presentation

## 编写书籍 {#sec-quarto-book}

Quarto Book 网页格式
