# 广义可加模型 {#sec-generalized-additive-models}

```{r}
#| echo: false

source("_common.R")
```

相比于广义线性模型，广义可加模型可以看作是一种非线性模型，模型中含有非线性的成分。

## 频率派

MASS 包的 mcycle 数据集

```{r}
#| label: fig-mcycle
#| fig-width: 5
#| fig-height: 4
#| fig-cap: mcycle 数据集
#| fig-showtext: true

data(mcycle, package = "MASS")
library(ggplot2)
ggplot(data = mcycle, aes(x = times, y = accel)) +
  geom_point() +
  theme_bw()
```

样条回归

```{r}
#| message: false

library(mgcv)
fgam <- gam(accel ~ s(times), data = mcycle, method = "REML")
summary(fgam)
```

方差成分

```{r}
gam.vcomp(fgam, rescale = FALSE)
```

```{r}
#| label: fig-mcycle-viz
#| fig-width: 5
#| fig-height: 4
#| fig-cap: mcycle 数据集
#| fig-showtext: true
#| par: true

plot(fgam)
```

## 贝叶斯派

```{r}
#| message: false

library(cmdstanr)
```

```{r}
#| eval: false

bgam <- brms::brm(accel ~ s(times),
  data = mcycle, family = gaussian(), cores = 2, seed = 20232023,
  iter = 4000, warmup = 1000, thin = 10, refresh = 0,
  control = list(adapt_delta = 0.99)
)
summary(bgam)
```

```{r}
#| eval: false
brms::fixef(bgam) # 固定效应
# brms::ranef(bgam) # 随机效应
```

```{r}
#| eval: false

ms_bgam <- brms::conditional_smooths(bgam) # 平滑效应
plot(ms_bgam)
```

```{r}
#| eval: false
brms::bayes_R2(bgam)
brms::waic(bgam)
# brms::log_lik(bgam)
brms::loo(bgam)
```

```{r}
#| eval: false
brms::pp_check(bgam, ndraws = 50)
```

```{r}
#| eval: false
brms::make_stancode(accel ~ s(times), data = mcycle, family = gaussian())
```
