# 数据操作 {#sec-data-manipulation}

目前， R 语言在数据操作方面陆续出现三套工具，最早的是 Base R（1997 年 4月），之后是 **data.table**（2006年4月） 和 **dplyr**（2014 年1月）。下面将从世界银行下载的原始数据开始，以各种数据操作及其组合串联起来介绍，完成数据探查的工作。

<!-- 
[SQL For the rest of us](https://technically.dev/posts/sql-for-the-rest-of-us.html)

关于 Base R 与 dplyr 的讨论
https://github.com/matloff/TidyverseSkeptic

本章不讨论矩阵、数组的操作
-->


## 操作工具 {#sec-tools}

本节所用数据来自世界银行，介绍 Base R、data.table、dplyr 的简介、特点、对比 

### Base R {#sec-base-r}

在 data.frame 的基础上，提供一系列辅助函数实现各类数据操作。

### data.table {#sec-data-table}

data.table 在 Base R 的基础上，扩展和加强了原有函数的功能，提供一套完整的链式操作语法。

### dplyr {#sec-dplyr}

**dplyr** 包提供一套全新的数据操作语法，与 **purrr** 包和 **tidyr** 包一起形成完备的数据操作功能。


### SQL {#sec-sql}


实际工作中，SQL （结构化查询语言）是必不可少的基础性工具，比如 [SQLite](https://sqlite.org/)、 [Hive](https://hive.apache.org/) 和 [Spark](https://spark.apache.org/sql/) 等都提供基于 SQL 的数据查询引擎，没有重点介绍 SQL 操作是因为本书以 R 语言为数据分析的主要工具，而不是它不重要。以 dplyr 来说吧，它的诸多语义动词就是对标 SQL 的。



## Base R 操作 {#sec-basic-operator}


介绍最核心的 Base R 数据操作，如筛选、排序、变换、聚合、重塑等


### 筛选 {#sec-select}

subset / `[`

### 变换 {#sec-transform}

最常见的变换操作是类型转化，比如从字符串型转为因子型、整型或日期型等。

within/transform

### 排序 {#sec-order}

order

### 聚合 {#sec-aggregation}

aggregate

### 合并 {#sec-merge}

merge


### 重塑 {#sec-reshape}

reshape


分组 split / lapply / do.call / Reduce

## data.table 操作 {#sec-data-table}

掌握此等基础性的工具，再去了解新工具也不难，更重要的是，只要将一种工具掌握的足够好，也就足以应付绝大多数的情况。

1. 介绍 data.table 基础语法，对标 Base R，介绍基础操作，同时给出等价的 dplyr 实现，但不运行代码。

1. data.table 扩展 Base R 数据操作，介绍常用的操作 8 个，讲清楚出现的具体场景，同时给出等价的 dplyr 实现，但不运行代码。

1. data.table 特有的高级数据操作 on .SD .I .J 等。


### 筛选 {#sec-dt-select}

`[`


### 变换 {#sec-dt-transform}

`:`


### 排序 {#sec-dt-order}


### 聚合 {#sec-dt-aggregate}


### 重塑 {#sec-dt-reshape}


### 合并 {#sec-dt-merge}



