---
title: "R Markdown 双栏排版"
subtitle: "副标题"
author: "张三"
date: "`r Sys.Date()`"
mathspec: yes
fontsize: 10pt
graphics: yes
lof: yes
geometry: margin=1.18in
output: 
  bookdown::pdf_book: 
    number_sections: yes
    toc: yes
    fig_crop: no
    latex_engine: xelatex
    base_format: rmarkdown::pdf_document
    citation_package: natbib
    template: null
    extra_dependencies:
      sourcecodepro:
       - scale=0.85
      ctex:
       - heading=true
       - fontset=fandol
      caption:
       - labelfont=bf
       - singlelinecheck=off
       - textfont=it
       - justification=centering
      Alegreya: null
keywords: 
  - 动态文档
  - 双栏排版
subject: "可重复研究与动态文档"
abstract: |
  这里是摘要内容
bibliography: 
 - packages.bib
biblio-style: plainnat
natbiboptions: "authoryear,round"
link-citations: true
colorlinks: true
classoption: "UTF8,a4paper,twocolumn"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R Markdown

R Markdown 文档混合了代码、图形和文字内容[@rmarkdown]。

## 代码 {#sec:code}

```{r cars}
summary(cars)
```

## 插图 {#sec:plot}

```{r}
#| fig-iris, 
#| fig.cap="鸢尾花数据集", 
#| fig.width=5, 
#| fig.height=4,
#| fig.showtext=TRUE, 
#| out.width="95%", 
#| echo=FALSE

library(ggplot2)
ggplot(iris, aes(Sepal.Length, Sepal.Width)) +
  geom_point(aes(colour = Species)) +
  scale_colour_brewer(palette = "Set1") +
  labs(
    title = "鸢尾花数据的散点图",
    x = "萼片长度", y = "萼片宽度", colour = "鸢尾花类别",
    caption = "鸢尾花数据集最早见于 Edgar Anderson (1935) "
  )
```

# 参考文献 {#chap:refer}
