name: Build-Docker

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    if: "contains(github.event.head_commit.message, '[docker]')"
    runs-on: ubuntu-22.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      QUARTO_VERSION: "1.3.361"
      CMDSTAN_VERSION: "2.32.2"
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./fedora_rstudio_pro.Dockerfile
          push: true
          tags: ghcr.io/xiangyunhuang/daar:latest,ghcr.io/xiangyunhuang/daar:1.0.0
          build-args: |
            QUARTO_VERSION=${{ env.QUARTO_VERSION }}
            CMDSTAN_VERSION=${{ env.CMDSTAN_VERSION }}
            GITHUB_PAT=${{ env.GITHUB_PAT }}
