name: Build-Docker

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Push image to GHCR
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/xiangyunhuang/daar:latest \
            --tag ghcr.io/xiangyunhuang/daar:1.0.0 \
            XiangyunHuang/daar:latest
