name: Build-Docker

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    if: "contains(github.event.head_commit.message, '[docker]')"
    runs-on: ubuntu-22.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RETICULATE_PYTHON_ENV: "/opt/.virtualenvs/r-tensorflow"
      CMDSTAN_VERSION: "2.31.0"
      CMDSTAN: "/opt/cmdstan/cmdstan-2.31.0"
      QUARTO_VERSION: "1.3.253"
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./fedora_rstudio_pro.Dockerfile
          push: true
          tags: xiangyunhuang/daar:1.0.0
          build-args: |
            CMDSTAN=${{ env.CMDSTAN }}
            CMDSTAN_VERSION=${{ env.CMDSTAN_VERSION }}
            RETICULATE_PYTHON_ENV=${{ env.RETICULATE_PYTHON_ENV }}
            QUARTO_VERSION=${{ env.QUARTO_VERSION }}
            GITHUB_PAT=${{ env.GITHUB_PAT }}
      -
        name: Push image to GHCR
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/xiangyunhuang/daar:latest \
            --tag ghcr.io/xiangyunhuang/daar:1.0.0 \
            xiangyunhuang/daar:1.0.0
