on:
  push:
    branches: main
  pull_request:
    branches: main
  # to be able to trigger a manual build
  workflow_dispatch:
  schedule:
    # 每周四 早上 7 点
    - cron: '0 23 * * 3'

name: Book-Fedora

env:
  isExtPR: ${{ github.event.pull_request.head.repo.fork == true }}
  RUST_BACKTRACE: 1

jobs:
  build-deploy:
    if: "!contains(github.event.head_commit.message, '[docker]')"
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/xiangyunhuang/daar:latest
      credentials:
         username: ${{ github.repository_owner }}
         password: ${{ secrets.GITHUB_TOKEN }}
      volumes:
        - ${{ github.workspace }}:/home/docker
      ports:
        - 8383:8787
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Render Book
        run: |
          # quarto render
          quarto render --to html

       - name: Git
         run: |
          git config --global user.email "xiangyunfaith@outlook.com"
          git config --global user.name "Xiangyun Huang"

      - name: Publish to Netlify (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Upload book folder for debug
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Upload Book
          path: _book
